---
stages:
- name: "Sonarqube source code scan"
  steps:
  - applyAppConfig:
      catalogTemplate: "cattle-global-data:iii-dev-charts3-scan-sonarqube"
      version: "0.1.0"
      name: "${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-sq"
      targetNamespace: "${CICD_GIT_REPO_NAME}"
      answers:
        git.branch: "${CICD_GIT_BRANCH}"
        git.commitID: "${CICD_GIT_COMMIT}"
        git.repoName: "${CICD_GIT_REPO_NAME}"
        git.url: "${CICD_GIT_URL}"
        pipeline.sequence: "${CICD_EXECUTION_SEQUENCE}"
        sonarqube.runnerVersion: 0.0.3
    when:
      branch:
        include:
        - "develop"
        - "scan"
- name: "Checkmarx source code scan"
  steps:
  - applyAppConfig:
      catalogTemplate: "cattle-global-data:iii-dev-charts3-scan-checkmarx"
      version: "0.1.0"
      name: "${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-cmx"
      targetNamespace: "${CICD_GIT_REPO_NAME}"
      answers:
        git.branch: "${CICD_GIT_BRANCH}"
        git.commitID: "${CICD_GIT_COMMIT}"
        git.repoName: "${CICD_GIT_REPO_NAME}"
        git.url: "${CICD_GIT_URL}"
        pipeline.sequence: "${CICD_EXECUTION_SEQUENCE}"
    when:
      branch:
        include:
        - "scan"
- name: "Build and push docker image"
  steps:
    - env:
        PLUGIN_BUILD_ARGS: "--progress=tty --network=host"
        PLUGIN_DEBUG: true
        PLUGIN_INSECURE: true
        PLUGIN_MIRROR: "https://harbor-demo.iiidevops.org"
        PLUGIN_MTU: 1000
      publishImageConfig:
        dockerfilePath: "./Dockerfile"
        buildContext: "."
        tag: "${CICD_GIT_REPO_NAME}/${CICD_GIT_BRANCH}:latest"
        pushRemote: true
        registry: "harbor-demo.iiidevops.org"
      when:
        branch:
          include:
            - "release"
- name: "Deploy app-webserver"
  steps:
    - applyAppConfig:
        catalogTemplate: "cattle-global-data:iii-dev-charts3-web"
        version: "0.5.0"
        name: "${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-web"
        targetNamespace: "${CICD_GIT_REPO_NAME}"
        answers:
          git.branch: "${CICD_GIT_BRANCH}"
          git.commitID: "${CICD_GIT_COMMIT}"
          git.repoName: "${CICD_GIT_REPO_NAME}"
          git.url: "${CICD_GIT_URL}"
          harbor.host: "harbor-demo.iiidevops.org"
          web.imageTag: "${CICD_GIT_REPO_NAME}/${CICD_GIT_BRANCH}:latest"
          web.port: 3000
      when:
        branch:
          include:
            - "release"

